apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wn3kf3qpp-nodejs 
  janus-idp.io/tekton: wn3kf3qpp-nodejs
  backstage.io/kubernetes-id: wn3kf3qpp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wn3kf3qpp-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  