apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wn3kf3qpp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wn3kf3qpp-nodejs 
  name: wn3kf3qpp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wn3kf3qpp-nodejs 
